# important for some providers to set e.g. the SOA record
nameserver: 'ddns.example.org.'

# important for some providers to set e.g. the SOA record
mailbox: 'hostmaster.example.org.'

users:
  - username: test
    password: test
    zones:
      - example.org.
      - sub.example.net.
